const ngoData = {
    Gujarat: [
      { name: 'MATRU SHRI ISHWARIBEN GULABRAY MEGHANI EDUCATION AND CHARITABLE TRUST', address: 'BANGLOW NO 6 GOVINDDHAM SOCIETY GANGA NAGAR CHOKADI NEW MAHILA COLLEGE ROAD VERAVAL', website: 'https://maathrusevatrust.org/', description: 'Animal Husbandry, Dairying & Fisheries,Children,Drinking Water,Education & Literacy,Housing,Information & Communication Technology,New & Renewable Energy,Tourism,Women s Development & Empowerment,Aged/Elderly,Environment & Forests,Health & Family Welfare,Labour & Employment,Land Resources,Legal Awareness & Aid,Micro Small & Medium Enterprises,Vocational Training,Water Resources,Any Othe' },
      { name: 'TRIBHUVAN EDUCATION TRUST', address: '42,UMA TENAMENT,NR SHILPAN SOCIETY,CHANDLODIA 382481', website: 'https://tribhuvandasfoundation.com/about-us/',description:'Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,Science & Technology,Women Development & Empowerment,Skill Development' },
      { name:'Vikram A Sarabhai Community Science Centre',address:'AHMEDABAD, Ahmedabad, GUJARAT',website:'http://www.vascsc.org',description:'Children,Education & Literacy,Environment & Forests,Information & Communication Technology,Science & Technology,Any Othe'},
      { name:'KAIRA SOCIAL SERVICE SOCIETY',address:', Nadiad, GUJARAT',website:'http://www.kairasociety.org',description:'Agriculture,Children,Civic Issues,Dalit Upliftment,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Legal Awareness & Aid,Micro Finance (SHGs),Micro Small & Medium Enterprises,Minority Issues,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Urban Development & Poverty Alleviation,Vocational Training,Women  Development & Empowerment,Youth Affairs'},
      { name:'Centre for Environment Education',address:'Ahmedabad, GUJARAT',website:'http://www.ceeindia.org',description:'Children,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Urban Development & Poverty Alleviation,Youth Affairs'},
      { name:'Hastkala Audhyogik Sahkari Mandali Ltd',address:', Bhuj, GUJARAT',website:'http://bhujhastkala.com',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises'},
      { name:'SHRI FARADI BHARATGUNTHAN MAHILA HASTKALA GRUHUDHYOG SAHKARI MANDALI LIMITEED',address:' MANDAVI, GUJARAT',website:'http://faradi.com',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises'},
    ],
    Maharashtra: [
      { name: 'shashwat foundation trust', address: 'E-28814, Mumbai, MAHARASHTRA', website: 'http://www.shashwatfoundation.org',description:'Rights,Information & Communication Technology,Labour & Employment,Land Resources,Legal Awareness & Aid,Micro Finance (SHGs),New & Renewable Energy,Nutrition,Rural Development & Poverty Alleviation,Science & Technology,Sports,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs' },
      { name: '	DWARKA BAHUDDESHIYA GRAMEEN VIKAS FOUNDATION BULDANA', address: ' BULDANA, MAHARASHTRA', website: 'http://rscp.ac.in/index.aspx?ReturnUrl=/',description:'Education & Literacy,Agriculture,Environment & Forests,Women Development & Empowerment' },
      { name: '	Principal Guru Nanak Khalsa College', address: 'Mumbai Maharashtra', website: 'https://gnkhalsa.edu.in/',description:'Art & Culture,Biotechnology,Education & Literacy,Environment & Forests,Science & Technology,Scientific & Industrial Research,Sports' },
      { name: 'Chikotra Shikshan Sanstha Kolhapur', address: 'KOLHAPUR, Kolhapur, MAHARASHTRA', website: 'http://chikotra.education',description:'Education & Literacy,Rural Development & Poverty Alleviation,Environment & Forests,Panchayati Raj,Agriculture' },
      { name: '	Amity University Maharashtra', address: 'Panvel, MAHARASHTRA', website: 'https://www.amity.edu/mumbai/contact-us',description:'Employment,Land Resources,Legal Awareness & Aid,Micro Finance (SHGs),Micro Small & Medium Enterprises,Minority Issues,New & Renewable Energy,Nutrition,Scientific & Industrial Research,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Youth Affairs,Panchayati Raj,Prisoner Issues,Right to Information & Advocacy,Rural Development & Poverty' },
      { name: '	Godbless Foundation', address: ', Pune, MAHARASHTRA', website: 'http://godblessfoundation.com/',description:'Education & Literacy,Aged/Elderly,Environment & Forests,Human Rights' },
      { name: 'AMRAPALI DNYANPRAKASH SHIKSHAN SANSTHA BELA', address: 'Bhandara Maharashtra', website: 'https://ngodetails.com/uncategorized/amrapali-dnyanprakash-shikshan-sanstha-bela/',description:'Education & Literacy,Minority Issues,Children,Dalit Upliftment,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Panchayati Raj,Science & Technology,Sports,Tribal Affairs,Vocational Training,Women Development & Empowerment,Youth Affairs,Any Other' },
    ],
    Goa: [
        { name: 'Amar Bharati Gram Vikas Sanstha', address: ' Bicholim, GOA', website: 'http://www.abgvs.blogspot.in',description:'Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Minority Issues,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Scientific & Industrial Research,Science ' },
        { name: 'Peaceful Society', address: 'Ponda Goa', website: 'http://www.peacefulsociety.org',description:'Literacy,Environment & Forests,Health & Family Welfare,Human Rights,Legal Awareness & Aid,Panchayati Raj,Rural Development & Poverty Alleviation,Water Resources,Women Development & Empowerment,Youth Affairs' },
        { name: 'Mineral Foundation of Goa', address: ' PANAJI, GOA', website: 'http://goamining.org/index.php/organisation/mf',description:'Literacy,Aged/Elderly,Environment & Forests,Health & Family Welfare,HIV/AIDS,Micro Finance (SHGs),Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Tourism' },
        { name: 'GOENCHINARISHAKTI', address: ' MAPUSA, GOA', website: 'http://www.goenchinarishakti.org.in',description:'Employment,Legal Awareness & Aid,Minority Issues,Nutrition,Panchayati Raj,Prisoner Issues,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Tourism,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment,Youth Affairs' },
        { name: 'SATGURU FOUNDATION', address: 'PONDA, GOA', website: 'http://www.srigurudev.org',description:'Agriculture,Art & Culture,Children,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,Micro Small & Medium Enterprises'},
        { name: 'Aggressive Goans', address: 'PONDA, GOA', website: 'https://www.aggressivegoans.org',description:'Agriculture,Art & Culture,Education & Literacy,Environment & Forests,Human Rights,Labour & Employment,Legal Awareness & Aid,New & Renewable Energy,Panchayati Raj,Prisoner Issues,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Women Development & Empowerment,Skill Development' },
        { name: 'I HELP FOUNDATION GOA', address: ' PORVORIM, GOA', website: 'http://www.ihelpfoundationgoa.com',description:'Environment & Forests,Women Development & Empowerment,Any Other,Children,Education & Literacy,Human Rights,Skill Development' },
        { name: 'Live Happy NGO', address: ' Mapusa, GOA', website: 'https://livehappygoa.com/',description:'Art & Culture,Children,Education & Literacy,Environment & Forests,Rural Development & Poverty Alleviation,Tourism' },
        { name: 'BITS Goa Innovation, Incubation & Entrepreneurship Society', address: 'Vasco da gama, GOA', website: 'https://www.bits-pilani.ac.in/Goa/BITSBIRAC/Home',description:'	Agriculture,Animal Husbandry, Dairying & Fisheries,Biotechnology,Environment & Forests,Food Processing,Health & Family Welfare,Information & Communication Technology,Micro Small & Medium Enterprises,Nutrition,Rural Development & Poverty Alleviation,Science & Technology,Scientific & Industrial Research,Women Development & Empowerment' },
        { name: 'MOHAMADEN EDUCATIONAL FOUNDATION', address: 'http://www.fatimaponda.com', website: 'http://www.fatimaponda.com',description:'Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Labour & Employment,Land Resources,Legal Awareness & Aid,Micro Finance (SHGs),Micro Small & Medium Enterprises,Minority Issues,New & Renewable Energy,Nutrition,Panchayati Raj,Prisoner Issues,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology,Scientific & Industrial Research,Sports,Tourism,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women  Development & Empowerment,Youth Affairs,Any Other,Skill Development' },
    ],
    Karnatka: [
        { name: 'SCODWES', address: ' Sirsi, KARNATAKA', website: 'http://www.scodwes.com',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Art & Culture,Children,Civic Issues,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Tribal Affairs,Tourism,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment' },
        { name: 'Agricultural Science Foundation', address: ' Dharwad, KARNATAKA', website: 'http://www.khpkvk.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Biotechnology,Environment & Forests,Food Processing,Health & Family Welfare,Land Resources,Micro Finance (SHGs),Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs' },
        { name: 'shimmer urban and rural development association', address: ', vijayapur, KARNATAKA', website: 'https://instagram.com/surda_karnataka?igshi',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Children,Education & Literacy,Environment & Forests,Health & Family Welfare,Labour & Employment,Micro Finance (SHGs),Minority Issues,New & Renewable Energy,Science & Technology,Sports,Tribal Affairs,Vocational Training,Women Development & Empowerment,Human Rights,Rural Development & Poverty Alleviation,Skill Development' },
        { name: 'Bhuvaneshwari Seva Samsthe', address: ' Hublii, KARNATAKA', website: 'http://www.bssgadag.com',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,Skill Development,Drinking Water,Education & Literacy,Food Processing,Women Development & Empowerment' },
        { name: 'JANAKALYAN', address: 'Sindhanur, KARNATAKA', website: 'http://www.jankalyana.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Children,Education & Literacy,Environment & Forests,Health & Family Welfare,Land Resources,Rural Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs,Art & Culture' },
        { name: 'Sarvodaya Service Society', address: ' Vijayapura, KARNATAKA', website: 'http://www.sarvoservicesocity.org	',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Biotechnology,Children,Differently Abled,Dalit Upliftment,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation' },
        { name: 'Vrutti', address: 'Bangalore, KARNATAKA', website: 'https://vruttiimpactcatalysts.org/',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Children,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Tribal Affairs,Tourism,Urban Development & Poverty Alleviation,Vocational Training' },
        { name: 'PARIVARTHANA RURAL DEVELOPMENT SOCIETY (R)', address: 'SHIRALAKOPPA, KARNATAKA', website: 'http://www.parivarthanango.com',description:'Aged/Elderly,Agriculture,Children,Differently Abled,Dalit Upliftment,Education & Literacy,Environment & Forests,Health & Family Welfare,Legal Awareness & Aid,Land Resources,Micro Finance (SHGs),Minority Issues,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs,Tribal Affairs' },
        { name: 'Belgaum Diocesan Social Service Society', address: ' Dharwad, KARNATAKA', website: 'http://ngo.india.gov.in',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Children,Differently Abled,Disaster Management,Dalit Upliftment,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Tribal Affairs,Urban Development & Poverty Alleviation' },
        { name: 'Taralabalu Rural Development Foundation', address: 'SIRIGERE, KARNATAKA', website: 'http://taralabalu.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Art & Culture,Civic Issues,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,Land Resources,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment' },
    ],
    Kerala: [
        { name: 'Centre for Rural Management', address: 'Kottayam, KERALA', website: 'http://www.crmindia.org',description:'Agriculture,Environment & Forests,Health & Family Welfare,Panchayati Raj,Rural Development & Poverty Alleviation,Tribal Affairs,Water Resources,Women Development & Empowerment,Any Other' },
        { name: 'Solidarity Movement of India', address: ', Idukki, KERALA', website: 'http://solidaritymovementofindia.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),New & Renewable Energy,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Tribal Affairs' },
        { name: 'SANTHIGIRI ASHRAM', address: ' THIRUVANANTHAPURAM, KERALA', website: 'http://www.santhigiriashram.org',description:'Agriculture,Animal Husbandry, Dairying & Fisheries,Art & Culture,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,Housing,Micro Small & Medium Enterprises,Rural Development & Poverty Alleviation,Scientific & Industrial Research,Tourism,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment,Youth Affairs' },
        { name: 'Arshabharath Bahujana Bodhavalkarana Gramavikasa', address: ', MEPPADI, KERALA', website: 'http://arshabharathindia.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Art & Culture,Children,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Prisoner Issues,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology' },
        { name: 'KOTTAYAM SOCIAL SERVICE SOCIETY', address: ', KOTTAYAM, KERALA', website: 'http://ksss.in',description:'Children,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,New & Renewable Energy,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs' },
        { name: 'Interagrated Development Center Thamarassery', address: 'Thamarassery, KERALA', website: 'http://www.idcthamarassery.com',description:'Agriculture,Art & Culture,Children,Civic Issues,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Rural Development & Poverty Alleviation,Sports,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment,Youth Affairs' },
        { name: 'VOSARD', address: 'Kumily, KERALA', website: 'http://www.vosard.org',description:'Animal Husbandry, Dairying & Fisheries,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Micro Finance (SHGs),New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology,Sports,Tribal Affairs,Tourism' },
        { name: 'The Dale View', address: ' Thiruvananthapuram, KERALA', website: 'http://www.daleview.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Children,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation' },
        { name: 'Punalur Social Service society', address: 'Punalur, KERALA', website: 'http://www.info@psssonline.com',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Children,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Labour & Employment,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Any Other' },
        { name: 'Centre for Innovation in Science and Social Action', address: 'Thiruvananthapuram, KERALA', website: 'http://www.cissa.co.in',description:'	Aged/Elderly,Agriculture,Children,Disaster Management,Drinking Water,Environment & Forests,Food Processing,Health & Family Welfare,Information & Communication Technology,Land Resources,New & Renewable Energy,Nutrition,Rural Development & Poverty Alleviation,Scientific & Industrial Research,Science & Technology,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment' },
    ],
    TamilNadu: [
        { name: 'ODAM', address: ' TIRUCHULI, TAMIL NADU', website: 'http://www.odamindia.org',description:'Aged/Elderly,Agriculture,Biotechnology,Children,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Scientific & Industrial Research,Science & Technology,Tribal Affairs,Vocational Training,Women  Development & Empowerment,Legal Awareness & Aid,Rural Development & Poverty Alleviation' },
        { name: 'Society for educational enviorinment and devlopmen', address: ', Karur, TAMIL NADU', website: 'https://seedngokarur.com/',description:'Agriculture,Education & Literacy,Biotechnology,Drinking Water,Aged/Elderly,Environment & Forests,Labour & Employment,New & Renewable Energy,Rural Development & Poverty Alleviation,Urban Development & Poverty Alleviation,Vocational Training' },
        { name: 'Athencottasan Muthamizh Kazhagam AMK', address: ', Kanyakumari, TAMIL NADU', website: 'http://www.amkcentre.org',description:'Aged/Elderly,Children,Differently Abled,Disaster Management,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Women  Development & Empowerment,Youth Affairs' },
        { name: 'Peoples Action for Development', address: ', MADURAI, TAMIL NADU', website: 'http://www.padgom.org',description:'Animal Husbandry, Dairying & Fisheries,Children,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Information & Communication Technology,Micro Finance (SHGs),Rural Development & Poverty Alleviation,Women Development & Empowerment,Youth Affairs' },
        { name: 'COMMUNITY ACTION FOR RURAL DEVELOPMENT SOCIETY', address: ' Gingee, TAMIL NADU', website: 'http://www.cardsngo.org',description:'Literacy,Environment & Forests,Rural Development & Poverty Alleviation,Tribal Affairs,Vocational Training,Women Development & Empowerment,Youth Affairs,Agriculture,Art & Culture,Biotechnology,Civic Issues,Disaster Management,Aged/Elderly,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Land Resources,Legal Awareness & Aid,Micro Finance (SHGs),Micro Small & Medium Enterprises,Minority Issues,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Science & Technology,Scientific & Industrial Research,Sports,Tourism,Urban Development & Poverty Alleviation,Water Resources' },
        { name: 'PUBLIC WELFARE and DEVELOPMENT SOCIETY', address: ', Erode, TAMIL NADU', website: 'http://www.ngo-pwdserode.in',description:'Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Right' },
        { name: 'Bharathamatha Family Welfare Foundation', address: ', Thiruthuraipundi, TAMIL NADU', website: 'http://ourbharathamatha.org',description:'Aged/Elderly,Agriculture,Children,Civic Issues,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Legal Awareness & Aid,Labour & Employment,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment,Youth Affairs,Any Other' },
        { name: 'Womens Education and Economic Development Society', address: ', Chennai, TAMIL NADU', website: 'http://www.weedsngo.org',description:'Aged/Elderly,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Tribal Affairs' },
        { name: 'SAMUGAM', address: ' Chennai, TAMIL NADU', website: 'http://www.samugam.com',description:'Agriculture,Biotechnology,Children,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,Panchayati Raj,Rural Development & Poverty Alleviation,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs' },
        { name: 'OMALUR BLOCK WOMEN WELFARE UPLIFT ORGANISATION', address: ' salem, TAMIL NADU', website: 'http://www.obwwuo.org',description:'Agriculture,Children,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Labour & Employment,Micro Finance (SHGs),Rural Development & Poverty Alleviation,Science & Technology,Tribal Affairs,Vocational Training,Women Development & Empowerment,Youth Affairs' },
    ],
    AndhraPradesh: [
        { name: 'MAHILA MARGADARSHI', address: 'Visakhapatnam, ANDHRA PRADESH', website: 'http://www.mahilamargadarshi.org',description:'Agriculture,Children,Dalit Upliftment,Drinking Water,Environment & Forests,Health & Family Welfare,Human Rights,Labour & Employment,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Water Resources,Women Development & Empowerment' },
        { name: 'SRI VINAYAKA RURAL DEVELOPMENT EDUCATIONAL SOCIETY', address: 'KURNOOL, ANDHRA PRADESH', website: 'https://svrdes.1ngo.in/',description:'Environment & Forests,Agriculture,Children,Dalit Upliftment,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,HIV/AIDS,Women Development & Empowerment' },
        { name: 'Gayatri Rural Educational Society', address: ' Srikakulam, ANDHRA PRADESH', website: 'http://www.gresindia.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises' },
        { name: 'Gowthami Foundation', address: ' Ongole, ANDHRA PRADESH', website: 'http://www.gowthamifoundation.org',description:'Aged/Elderly,Agriculture,Art & Culture,Children,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Micro Finance (SHGs),Minority Issues,New & Renewable Energy,Nutrition,Rural Development & Poverty Alleviation,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women  Development & Empowerment,Youth Affairs,Any Other' },
        { name: 'RASHTRIYA SEVA SAMITHI RASS', address: ' TIRUPATI, ANDHRA PRADESH', website: 'http://www.rassngo.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Information & Communication Technology,Legal Awareness & Aid,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Right to Information & Advocacy,Rural Development & Poverty Alleviation' },
        { name: 'Sri Swarupa Nistha Ashrama Philosophical Welfare Society', address: ' Kadiri, ANDHRA PRADESH', website: 'http://www.snapsindia.org',description:'Animal Husbandry, Dairying & Fisheries,Education & Literacy,Environment & Forests,Minority Issues,Science & Technology,Vocational Training,Any Other' },
        { name: 'socialworkoraganisation', address: ' ELURU, ANDHRA PRADESH', website: 'http://www.swongo.ngo',description:'Nutrition,Agriculture,Children,Civic Issues,Dalit Upliftment,Differently Abled,Aged/Elderly,Environment & Forests,Food Processing,Health & Family Welfare,Legal Awareness & Aid,Micro Small & Medium Enterprises,Rural Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment' },
        { name: 'HOLY CROSS SOCIAL SERVICE SOCIETY', address: ' Srikakulam, ANDHRA PRADESH', website: 'http://www.holycross.org.in',description:'Disaster Management,Education & Literacy,Environment & Forests,HIV/AIDS,Housing,Rural Development & Poverty Alleviation,Tribal Affairs,Vocational Training,Water Resources,Women  Development & Empowerment' },
        { name: 'Sri Venkateswara Anadha Seva Sadan', address: 'Chittoor, ANDHRA PRADESH', website: 'http://www.svassindia.org',description:'Children,Education & Literacy,Environment & Forests,Health & Family Welfare,Rural Development & Poverty Alleviation,Science & Technology,Women Development & Empowerment,Agriculture,Art & Culture,Any Other,Skill Development' },
        { name: 'Visishta Gramodaya Swayam Sadhana Parishad', address: ' Visakhapatnam, ANDHRA PRADESH', website: 'http://www.vgssp.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy' },
    ],
    Odisha: [
        { name: 'PRERANA', address: 'BOLANGIR, ORISSA', website: ' https://www.odishanews24.in',description:'Agriculture,Animal Husbandry, Dairying & Fisheries,Art & Culture,Children,Differently Abled,Drinking Water,Education & Literacy,Aged/Elderly,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Labour & Employment,Micro Small & Medium Enterprises,New & Renewable Energy,Panchayati Raj,Scientific & Industrial Research,Water Resources,Women Development & Empowerment' },
        { name: 'DEVELOPMENT RESOURCE CENTRE', address: ' PURI, ORISSA', website: 'http://www.drcorissa.weebly.com',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy' },
        { name: 'JANA SWASTHYA SEVA SANSTHA', address: 'Bhawanipatna, ORISSA', website: 'http://www.jsssodisha.org',description:'Environment & Forests,Health & Family Welfare,HIV/AIDS,Nutrition,Science & Technology,Sports,Vocational Training,Women  Development & Empowerment,Youth Affairs,Food Processing' },
        { name: 'MAYURBHANJ BIOLOGICAL RESEARCH', address: 'BARIPADA, ORISSA', website: 'http://www.mbrindia.org',description:'Agriculture,Art & Culture,Biotechnology,Children,Dalit Upliftment,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Information & Communication Technology,Labour & Employment,Land Resources,New & Renewable Energy,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Scientific & Industrial Research,Tourism,Tribal Affairs,Vocational Training,Water Resources,Women  Development & Empowerment' },
        { name: 'Voluntary Association for Rural Development', address: ', Baripada, ORISSA', website: 'https://www.vardodisha.org/',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises' },
        { name: 'Leading Organisation For Rural Development', address: ' Dhenkanal, ORISSA', website: 'http://www.lordodisha.org',description:'Animal Husbandry, Dairying & Fisheries,Art & Culture,Children,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Labour & Employment,Panchayati Raj,Rural Development & Poverty Alleviation,Sports,Tribal Affairs,Women Development & Empowerment,Youth Affairs,Education & Literacy,Vocational Training,Micro Finance (SHGs),Women Development & Empowerment' },  
        { name: 'Ekta', address: 'Bhubaneshwar, ORISSA', website: 'http://www.ekta.org.in',description:'Agriculture,Children,Differently Abled,Disaster Management,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Land Resources,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology,Tribal Affairs,Vocational Training,Women  Development & Empowerment,Youth Affairs' },
        { name: 'BHAIRABI CLUB', address: 'KHORDHA, ORISSA', website: 'http://www.bhairabiclub.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Children,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Legal Awareness & Aid,Labour & Employment,Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Sports,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment' },
        { name: 'centre for rehabilitation services and research', address: ' Bhadrak, ORISSA', website: 'http://www.crsr.org.in',description:'Aged/Elderly,Children,Differently Abled,Disaster Management,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Information & Communication Technology,Legal Awareness & Aid,Micro Finance (SHGs),Nutrition,Panchayati Raj,Rural Development & Poverty Alleviation,Science & Technology,Tribal Affairs,Vocational Training,Women  Development & Empowerment,Youth Affairs' },
        { name: 'ASSOCIATION FOR VOLUNTARY ACTION', address: 'PURI, ORISSA', website: 'http://www.avaodisha.org',description:'Aged/Elderly,Agriculture,Children,Differently Abled,Disaster Management,Dalit Upliftment,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Human Rights,Legal Awareness & Aid,Labour & Employment,Micro Finance (SHGs),Right to Information & Advocacy,Rural Development & Poverty Alleviation,Sports,Tribal Affairs,Vocational Training,Women  Development & Empowerment,Youth Affairs' },
    ],
    WestBengal: [
        { name: 'TUFANGANJ ANWESHA WELFARE SOCIETY', address: ' TUFANGANJ, WEST BENGAL', website: 'http://www.anwesha.org.in',description:'Women Development & Empowerment,Agriculture,Animal Husbandry, Dairying & Fisheries,Education & Literacy,Aged/Elderly,Environment & Forests,Food Processing,Rural Development & Poverty Alleviation,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Art & Culture,Biotechnology,Drinking Water,Health & Family Welfare,HIV/AIDS,Micro Small & Medium Enterprises,New & Renewable Energy,Panchayati Raj,Tribal Affairs,Children,Land Resources,Science & Technology' },
        { name: 'Sabuj Sangha', address: ' Kolkata, WEST BENGAL', website: 'http://www.sabujsangha.org',description:'	Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Housing,Civic Issues,Micro Finance (SHGs),Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology,Sports,Tourism,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Youth Affairs' },
        { name: 'Lokamata Rani Rashmoni Mission', address: ' Nimpith, WEST BENGAL', website: 'http://www.rashmoni.org.in',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Children,Drinking Water,Education & Literacy,Environment & Forests,Health & Family Welfare,HIV/AIDS,Legal Awareness & Aid,Labour & Employment,Micro Finance (SHGs),Minority Issues,Rural Development & Poverty Alleviation,Vocational Training,Wome  Development & Empowerment,Youth Affairs' },
        { name: 'ISLAMPUR RAMKRISHNAPALLY RURAL WELFARE SOCIETY', address: ' Islampur, WEST BENGAL', website: 'http://www.irrwsngo.org',description:'Aged/Elderly,Agriculture,Art & Culture,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy,Nutrition,Panchayati Raj' },
        { name: 'TAJMAHAL GRAM BIKASH KENDRA', address: ' Howrah, WEST BENGAL', website: 'http://www.tgbk.org',description:'Children,Dalit Upliftment,Differently Abled,Drinking Water,Education & Literacy,Aged/Elderly,Environment & Forests,Health & Family Welfare,HIV/AIDS,Information & Communication Technology,Legal Awareness & Aid,Minority Issues,New & Renewable Energy,Nutrition,Panchayati Raj,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Science & Technology,Sports,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Women Development & Empowerment,Youth Affairs' },
        { name: 'Chiranabin', address: ', Kolkata, WEST BENGAL', website: 'http://www.Chiranabin.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Children,Civic Issues,Differently Abled,Drinking Water,Education & Literacy,Health & Family Welfare,Legal Awareness & Aid,Nutrition,Rural Development & Poverty Alleviation,Sports,Tribal Affairs,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women  Development & Empowerment,Youth Affairs,Agriculture,Environment & Forests,Micro Small & Medium Enterprises' },
        { name: 'HOWRAH GREEN WORLD', address: ', HOWRAH, WEST BENGAL', website: 'http://www.howrahgreenworld.org',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Civic Issues,Differently Abled,Disaster Management,Dalit Upliftment,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Information & Communication Technology,Legal Awareness & Aid,Labour & Employment,Land Resources,Minority Issues,Micro Small & Medium Enterprises,New & Renewable Energy' },
        { name: 'Dantan Manav Kalyan Kendra', address: ' Kolkata, WEST BENGAL', website: 'http://www.dmkk.org.in',description:'Animal Husbandry, Dairying & Fisheries,Aged/Elderly,Agriculture,Art & Culture,Biotechnology,Children,Differently Abled,Drinking Water,Education & Literacy,Environment & Forests,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Micro Finance (SHGs),Minority Issues,Micro Small & Medium Enterprises,Nutrition,Right to Information & Advocacy,Rural Development & Poverty Alleviation,Sports,Tribal Affairs,Vocational Training,Animal Husbandry, Dairying & Fisheries,Differently Able' },
        { name: 'INDIAN RESEARCH INSTITUTE FOR INTEGRATED MEDICINE', address: ' Howrah, WEST BENGAL', website: 'http://www.iriim.org',description:'Health & Family Welfare,HIV/AIDS,Scientific & Industrial Research,Science & Technology,Any Other,Biotechnology,Differently Abled,Disaster Management,Education & Literacy,Aged/Elderly,Environment & Forests,New & Renewable Energy,Nutrition,Vocational Training,Women Development & Empowerment ' },
        { name: 'Barasat Unnayan Prostuti', address: ', Kolkata, WEST BENGAL', website: 'http://www.snws.co.in',description:'Agriculture,Art & Culture,Children,Disaster Management,Drinking Water,Education & Literacy,Food Processing,Health & Family Welfare,HIV/AIDS,Housing,Human Rights,Legal Awareness & Aid,Micro Finance (SHGs),Rural Development & Poverty Alleviation,Sports,Tourism,Urban Development & Poverty Alleviation,Vocational Training,Water Resources,Women Development & Empowerment,Any Other,Animal Husbandry, Dairying & Fisheries,Biotechnology,Civic Issues,Aged/Elderly,Environment & Forests,Information & Communication Technology,Minority Issues,New & Renewable Energy,Science & Technology,Tribal Affairs ' },
    ],
              
      
      
  };
  function selectState(state) {
    const ngoListContainer = document.getElementById('ngo-list');
    ngoListContainer.innerHTML = '';

    const listItems = document.querySelectorAll('#state-list li');
    
    listItems.forEach(item => item.classList.remove('selected'));

    const clickedItem = document.querySelector(`#state-list li[data-state='${state}']`);
    clickedItem.classList.add('selected');

    showNGOs(state);
}
  
  function showNGOs(state) {
    const ngoListContainer = document.getElementById('ngo-list');
    ngoListContainer.innerHTML = ''; 
    if (ngoData[state]) {
      ngoData[state].forEach((ngo) => {
        const row = document.createElement('tr');
        row.innerHTML = `
          <td>${ngo.name}</td>
          <td>${ngo.address}</td>
          <td><a href="${ngo.website}" target="_blank">${ngo.website}</a></td>
          <td>${ngo.description}</td>
        `;
        ngoListContainer.appendChild(row);
      });
    }
  }
// scroll 
function scrollStateList(direction) {
  const stateListContainer = document.getElementById('state-list-container');
  const scrollAmount = 200;
  if (direction === 'left') {
    stateListContainer.scrollLeft -= scrollAmount;
  } else if (direction === 'right') {
    stateListContainer.scrollLeft += scrollAmount;
  }
}

document.addEventListener('keydown', function (event) {
  const stateListContainer = document.getElementById('state-list-container');

  if (event.key === 'ArrowLeft') {
    scrollStateList('left');
  } else if (event.key === 'ArrowRight') {
    scrollStateList('right');
  }
});